title: <p align="center"> Erik Magnusson </p>

logo: "/images/hiking.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Erik_Magnusson_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/elmagnusson/">LinkedIn</a> |
  <a href="https://github.com/emagnusson88">GitHub</a>
  </p>
  
  <p align="justify">
  I am data scientist with recent work on time series forecasting, generative models, and deep learning.
  <br><br>
  M.S. Analytics | Georgia Tech
  <br><br>
  B.S. Systems Engineering | U. of Virginia
  <br><brb>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-JL0XFB972K # Google Analytics tracking ID
