title: <p align="center"> Erik Magnusson </p>

logo: "/images/hiking.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Erik_Magnusson_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/elmagnusson/">LinkedIn</a> |
  <a href="https://github.com/emagnusson88">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursuing a M.S. in Computational Data Analytics at the Georgia Institute of Technology.
  <br><br>
  My recent work has focused on NLP, reinforcement learning, and infectious disease forecasting. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-JL0XFB972K # Google Analytics tracking ID
