title: <p align="center"> Erik Magnusson </p>

logo: "/images/hiking.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Erik_Magnusson_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/elmagnusson/">LinkedIn</a> |
  <a href="https://github.com/emagnusson88">GitHub</a>
  </p>
  
  <p align="justify">
  I am data scientist with recent work on time series forecasting, generative models, and deep learning.
  
  pursuing a M.S. in Computational Data Analytics at the Georgia Institute of Technology.
  B.S. Systems Engineering | University of Virginia
  M.S. Analytics | Georgia Tech
  <br><br>
  My recent work has focused on time series forecasting,  NLP, reinforcement learning, and infectious disease forecasting. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-JL0XFB972K # Google Analytics tracking ID
